### ISSUE TITLE
Icons (images) cannot be displayed

### ISSUE THREAD

**Issue by iseruuuuu** [NirmalScaria/label_marker#4]
Icons (images) cannot be displayed.

Code
```
markers.addLabelMarker(LabelMarker(
    label: "shop",
    markerId: MarkerId("id"),
    position: LatLng(10.0, 11.0),
    icon: await google.BitmapDescriptor.fromAssetImage(
            const ImageConfiguration(devicePixelRatio: 10),
            'assets/images/map/pin.png'),
    backgroundColor: Colors.green,
    )).then((value) {
    setState(() {});
    },
);
```

The label is displayed properly, but the icon is not.
Assets are loading properly.

**Comment by Satid** [comment]
i am found this issue same can you help me please

**Comment by NirmalScaria** [comment]
This package is meant to add text label markers only. So,  the "icon" parameter inside the LabelMarker() is a totally pointless parameter. It does nothing. (I will remove it in the next version, to avoid confusion). 

The actual icon that is added to google map by this package is an internally generated icon within the package, which will be the text and the border/background around the text.

If you want to add an icon next to it, you will have to find some workaround. Maybe add another marker which is just the icon. Or make changes to the source code of the extension to add an icon to the marker.

@Satid  @iseruuuuu

**Comment by Satid** [comment]
Thank you very much Sir

From: Nirmal Scaria ***@***.***>
Date: Monday, 31 October BE 2565 17:48
To: NirmalScaria/label_marker ***@***.***>
Cc: Satid Seenun ***@***.***>, Mention ***@***.***>
Subject: Re: [NirmalScaria/label_marker] Icons (images) cannot be displayed (Issue #4)

This package is meant to add text label markers only. So, the "icon" parameter inside the LabelMarker() is a totally pointless parameter. It does nothing. (I will remove it in the next version, to avoid confusion).

The actual icon that is added to google map by this package is an internally generated icon within the package, which will be the text and the border/background around the text.

If you want to add an icon next to it, you will have to find some workaround. Maybe add another marker which is just the icon. Or make changes to the source code of the extension to add an icon to the marker.

@Satid<https://github.com/Satid> @iseruuuuu<https://github.com/iseruuuuu>
